---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-13.04
  driver_config:
    box: opscode-ubuntu-13.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
  run_list:
    - recipe[apt]

- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
    - recipe[apt]

suites:
- name: default
  run_list:
    - recipe[golang_test::default]
    - recipe[minitest-handler]
  attributes: {}

