source "https://supermarket.getchef.com"

cookbook 'ark'
cookbook 'build-essential'
cookbook 'collectd', github: 'hectcastro/chef-collectd'
cookbook 'elasticsearch', github: 'elasticsearch/cookbook-elasticsearch'
cookbook 'ipaddr_extensions'
cookbook 'java'
cookbook 'mosh'
cookbook 'rsyslog'
cookbook 'sysctl'
cookbook 'td-agent', github: 'treasure-data/chef-td-agent'
cookbook 'ulimit'
cookbook 'opsworks_wordpress', github: 'polydice/opsworks_wordpress'
cookbook 'thumbor_ng', github: 'vkhatri/chef-thumbor-ng'
