source 'https://api.berkshelf.com'

cookbook 'ark'
cookbook 'build-essential'
cookbook 'dokku'
cookbook 'elasticsearch'
cookbook 'ipaddr_extensions'
cookbook 'java'
cookbook 'mosh'
cookbook 'redisio'
cookbook 'rsyslog'
cookbook 'sysctl'
cookbook 'ulimit'
