source "https://rubygems.org"

gem "chef", ">= 0.10.8", "< 11.0.0"
gem "foodcritic"
gem "growl"
gem "guard"
gem "guard-bundler"
gem "guard-foodcritic"
gem "guard-rspec"
gem "rake"
gem "rb-fsevent"
gem "rspec"
gem "scout"
