maintainer        "Polydice Inc."
maintainer_email  "bert@thepolydice.com"
license           "Apache 2.0"
description       "Install and deploy knife (go) web applications."
version           "0.0.1"
recipe            "knife::configure", "configure folders"
recipe            "knife::deploy", "deploy app"
recipe            "knife::restart", "restart server"
recipe            "knife::rollback", "rollback the app"
recipe            "knife::stop", "stop server"
recipe            "knife::undeploy", "undeploy the app"
depends           "golang"
depends           "monit"
depends           "deploy"
