maintainer        "Polydice Inc."
maintainer_email  "bert@thepolydice.com"
license           "Apache 2.0"
description       "Install and deploy knife (go) web applications."
version           "0.0.1"
recipe            "knife::configure"
recipe            "knife::deploy"
recipe            "knife::restart"
recipe            "knife::rollback"
recipe            "knife::stop"
recipe            "knife::undeploy"
depends           "golang"
depends           "monit"
depends           "deploy"
